const GET_PLACES = 'GET_PLACES';
const SET_CURRENT_PLACE = 'SET_CURRENT_PLACE';
const SET_PLACES = 'SET_PLACES';
const GET_AIR_POLLUTION_BY_IP = 'GET_AIR_POLLUTION_BY_IP';
const SET_AIR_POLLUTION_INFO = 'SET_AIR_POLLUTION_INFO';

export {
  GET_PLACES,
  SET_CURRENT_PLACE,
  SET_PLACES,
  GET_AIR_POLLUTION_BY_IP,
  SET_AIR_POLLUTION_INFO,
};
