const GET_PLACES = 'GET_PLACES';
const SET_PLACES = 'SET_PLACES';
const SET_CURRENT_PLACE = 'SET_CURRENT_PLACE';
const GET_INFO_BY_IP = 'GET_INFO_BY_IP';
const SET_AIR_POLLUTION_INFO = 'SET_AIR_POLLUTION_INFO';
const SET_WEATHER_INFO = 'SET_WEATHER_INFO';
const SET_THEME = 'SET_THEME';

export {
  GET_PLACES,
  SET_CURRENT_PLACE,
  SET_PLACES,
  GET_INFO_BY_IP,
  SET_AIR_POLLUTION_INFO,
  SET_WEATHER_INFO,
  SET_THEME,
};
